# Generated by Django 3.0.6 on 2020-05-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmgsys', '0004_auto_20200529_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='product_id',
        ),
        migrations.AddField(
            model_name='workorder',
            name='product_id',
            field=models.ManyToManyField(null=True, to='invmgsys.Product'),
        ),
    ]
