# Generated by Django 3.0.6 on 2020-05-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmgsys', '0005_auto_20200529_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='product_id',
            field=models.ManyToManyField(to='invmgsys.Product'),
        ),
    ]
