# Generated by Django 3.0.6 on 2020-05-29 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invmgsys', '0006_auto_20200529_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='product_id',
        ),
        migrations.AddField(
            model_name='workorder',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invmgsys.Product'),
        ),
    ]
